In [16]:
import pandas as pd
import pprint

In [17]:
csv_file = 'data_files/malaria_data.csv'
malaria_df = pd.read_csv(csv_file)

In [18]:
malaria_df

,Year,Argentina,Belize,Bolivia,Brazil,Colombia,Costa Rica,Dominican Republic,Ecuador,El Salvador,...,Guyana,Haiti,Honduras,Mexico,Nicaragua,Panama,Paraguay,Peru,Suriname,Venezuela
0,2000,440.0,1486.0,31469.0,613241.0,144432.0,1879.0,1233.0,104528.0,753.0,...,24018.0,16897.0,35125.0,7390.0,23878.0,1036.0,6853.0,68321.0,11361.0,29736.0
1,2001,215.0,1162.0,15765.0,388303.0,231233.0,1363.0,1038.0,108903.0,362.0,...,27122.0,9837.0,24149.0,4996.0,10482.0,928.0,2710.0,78544.0,16003.0,20006.0
2,2002,125.0,1134.0,14276.0,348259.0,204916.0,1021.0,1296.0,86757.0,117.0,...,21895.0,9837.0,17223.0,4624.0,7695.0,2244.0,2778.0,99237.0,12837.0,29491.0
3,2003,124.0,1084.0,20343.0,408886.0,180956.0,718.0,1529.0,52065.0,85.0,...,27627.0,9837.0,14123.0,3819.0,6717.0,4500.0,1392.0,88408.0,10982.0,31719.0
4,2004,116.0,1066.0,14910.0,465004.0,142241.0,1289.0,2355.0,28730.0,112.0,...,28866.0,10802.0,17293.0,3406.0,6897.0,5095.0,694.0,93581.0,8378.0,46655.0
5,2005,252.0,1549.0,21442.0,606067.0,121629.0,3541.0,3837.0,17050.0,67.0,...,38984.0,21778.0,16007.0,2967.0,6642.0,3667.0,373.0,87699.0,9131.0,45049.0
6,2006,212.0,844.0,19725.0,549469.0,120096.0,2903.0,3525.0,9863.0,49.0,...,21064.0,32739.0,11923.0,2514.0,3114.0,1663.0,823.0,64925.0,3289.0,37062.0
7,2007,355.0,845.0,14610.0,458652.0,128462.0,1223.0,2711.0,8194.0,40.0,...,11656.0,29825.0,10513.0,2361.0,1356.0,1281.0,1341.0,50797.0,2797.0,41749.0
8,2008,106.0,540.0,9748.0,315746.0,80559.0,966.0,3680.0,4891.0,33.0,...,11815.0,36774.0,8368.0,2357.0,762.0,744.0,348.0,83354.0,4203.0,32037.0
9,2009,136.0,512.0,19486.0,309316.0,158694.0,524.0,3286.0,4126.0,40.0,...,13673.0,49535.0,18634.0,5406.0,610.0,1556.0,182.0,79667.0,4879.0,71656.0
10,2010,72.0,300.0,27538.0,669335.0,235300.0,228.0,5896.0,3776.0,48.0,...,45870.0,84153.0,19427.0,2459.0,1384.0,836.0,54.0,63091.0,3483.0,90310.0
11,2011,36.0,158.0,14286.0,534292.0,128745.0,34.0,3232.0,2464.0,31.0,...,58942.0,68700.0,15260.0,2254.0,1850.0,708.0,20.0,50044.0,1566.0,91648.0
12,2012,8.0,74.0,14830.0,485516.0,120358.0,16.0,1904.0,1116.0,42.0,...,63202.0,55732.0,12902.0,1675.0,2470.0,1688.0,30.0,63006.0,1123.0,105606.0
13,2013,8.0,52.0,15754.0,356313.0,103418.0,12.0,1158.0,756.0,14.0,...,62958.0,41914.0,10856.0,998.0,2390.0,1410.0,22.0,86607.0,1458.0,157286.0
14,2014,8.0,38.0,14802.0,286830.0,81536.0,12.0,992.0,484.0,16.0,...,24706.0,35392.0,6862.0,1328.0,2326.0,1748.0,16.0,114040.0,802.0,181416.0
15,2015,2.0,26.0,13814.0,286211.0,107460.0,16.0,1322.0,1372.0,18.0,...,19968.0,35166.0,7150.0,1102.0,4614.0,1124.0,16.0,133218.0,752.0,272804.0
16,2016,2.0,10.0,11106.0,258501.0,146397.0,26.0,1510.0,2848.0,28.0,...,23475.0,43428.0,8435.0,1192.0,12568.0,1622.0,21.0,113246.0,654.0,481226.0
17,2017,33.0,18.0,9174.0,388740.0,97507.0,50.0,796.0,2879.0,8.0,...,27872.0,37978.0,2574.0,1530.0,21898.0,1378.0,10.0,113059.0,1102.0,829054.0
18,Total,2250.0,10898.0,303078.0,7728681.0,2533939.0,16821.0,41300.0,440802.0,1863.0,...,553713.0,610650.0,256824.0,52378.0,117653.0,33228.0,17683.0,1530844.0,94800.0,2594510.0

In [19]:
malaria_df.columns[0]

'Year'

In [23]:
geoJSON = {
    "type": "Feature Collection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "name": malaria_df.columns[1],
                "coordinates": ['lat','long']
            },
            "properties": {
                "incidents": malaria_df[malaria_df.columns[1]]
            }
        }
    ]
}

In [24]:
geoJSON

{'type': 'Feature Collection', 'features': [{'type': 'Feature', 'geometry': {'name': 'Argentina', 'coordinates': ['lat', 'long']}, 'properties': {'incidents': 0      440.0
1      215.0
2      125.0
3      124.0
4      116.0
5      252.0
6      212.0
7      355.0
8      106.0
9      136.0
10      72.0
11      36.0
12       8.0
13       8.0
14       8.0
15       2.0
16       2.0
17      33.0
18    2250.0
Name: Argentina, dtype: float64}}]}